select 

typeid,
avg(car_age) car_age,
avg(cpi) cpi,
cylinder_capacity,
cc_unit,
real_cylinder_capacity,
brand_txt,
type_txt,
model_txt,
avg(year) year, 
gearbox_type,
gps,
avg(guide_price) guide_price,
avg(guide_day_price) guide_day_price,
avg(hour_price) hour_price,
avg(day_price) day_price,
avg(week_price) week_price,
avg(holiday_price) holiday_price,
ly_car_param_source,
car_cate,
avg(req_count) req_count,
avg(req_count_uv) req_count_uv,
avg(settle_trans_count) settle_trans_count,
avg(halfyear_settletrans_count) halfyear_settletrans_count,
avg(1year_settletrans_count) 1year_settletrans_count,
avg(successtrans_count) successtrans_count,
avg(halfyear_successtrans_count) halfyear_successtrans_count,
avg(1year_successtrans_count) 1year_successtrans_count,
avg(break_count) break_count,
avg(success_rent_day) success_rent_day,
avg(halfyear_success_rentday) halfyear_success_rentday,
avg(1year_success_rentday) 1year_success_rentday,
avg(refuse_count) refuse_count,
avg(1year_refuse_count) 1year_refuse_count,
avg(halfyear_refuse_count) halfyear_refuse_count,
avg(owner_cancel_count) owner_cancel_count,
avg(1year_owner_cancel_count) 1year_owner_cancel_count,
avg(halfyear_owner_cancel_count) halfyear_owner_cancel_count,
avg(renter_cancel_count) renter_cancel_count,
avg(1year_renter_cancel_count) 1year_renter_cancel_count,
avg(halfyear_renter_cancel_count) halfyear_renter_cancel_count,
avg(total_show_num) total_show_num,
avg(90day_show_num) 90day_show_num,
avg(total_favorit_num) total_favorit_num,
avg(90day_favorit_num) 90day_favorit_num,
avg(total_click_num) total_click_num,
avg(total_click_num_all) total_click_num_all,
avg(total_click_num_uv_all) total_click_num_uv_all,
avg(90day_click_num) 90day_click_num,
avg(placeorder_num) placeorder_num,
avg(placeorder_num_uv) placeorder_num_uv

from

(select t2.type typeid, t1.*  from bi.mid0_report_car t1,bi.car t2 where t1.reg_no = t2.reg_no and t2.type is not null) as T1

group by typeid 

